version: '3'
services:
  server:
    image: fchat-server
    depends_on:
      - db
    ports:
      - '4040:4040'
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; ./main'
  db:
    image: postgres
    environment:
      POSTGRES_DB: fchat_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  client:
    image: fchat-ui
    ports:
      - '8080:8080'
